### ISSUE TITLE
Fix answer checking in Lab 2

### ISSUE THREAD

**Issue by nussisthebaum** [nussisthebaum/DATA119-Labs#9]
Currently not working even when students copy and paste solutions.

**Comment by nussisthebaum** [comment]
@amandakube Just want to document what happened--we think this was an issue from trying to fix that Python null error and was mostly addressed by editing the setup chunk?

**Comment by amandakube** [comment]
I had added some code in the custom_checker function when I was troubleshooting the Python null error. That code did not fix the error and, in fact, just caused more errors. It didn't output the expected objects, which caused the answer checker to break.
